package constant

const (
	PROPERTY_KEYS = "KEYS"
	PROPERTY_TAGS = "TAGS"
	PROPERTY_WAIT_STORE_MSG_OK = "WAIT"
	PROPERTY_DELAY_TIME_LEVEL = "DELAY"
	PROPERTY_RETRY_TOPIC = "RETRY_TOPIC"
	PROPERTY_REAL_TOPIC = "REAL_TOPIC"
	PROPERTY_REAL_QUEUE_ID = "REAL_QID"
	PROPERTY_TRANSACTION_PREPARED = "TRAN_MSG"
	PROPERTY_PRODUCER_GROUP = "PGROUP"
	PROPERTY_MIN_OFFSET = "MIN_OFFSET"
	PROPERTY_MAX_OFFSET = "MAX_OFFSET"
	PROPERTY_BUYER_ID = "BUYER_ID"
	PROPERTY_ORIGIN_MESSAGE_ID = "ORIGIN_MESSAGE_ID"
	PROPERTY_TRANSFER_FLAG = "TRANSFER_FLAG"
	PROPERTY_CORRECTION_FLAG = "CORRECTION_FLAG"
	PROPERTY_MQ2_FLAG = "MQ2_FLAG"
	PROPERTY_RECONSUME_TIME = "RECONSUME_TIME"
	PROPERTY_MSG_REGION = "MSG_REGION"
	PROPERTY_UNIQ_CLIENT_MESSAGE_ID_KEYIDX = "UNIQ_KEY"
	PROPERTY_MAX_RECONSUME_TIMES = "MAX_RECONSUME_TIMES"
	PROPERTY_CONSUME_START_TIMESTAMP = "CONSUME_START_TIME"

	COMMUNICATIONMODE_SYNC = "SYNC"
	COMMUNICATIONMODE_ASYNC = "ASYNC"
	COMMUNICATIONMODE_ONEWAY = "ONEWAY"
)
