@startuml
Rebalance ->Rebalance:for each topic in Subscription
Rebalance->MqClient:findConsumerIdList(topic,group)
Rebalance->MqClient:GetTopicSubscribeInfo(topic)
Rebalance->AllocateMessageQueueStrategy:allocate with all consumer client List and all queue info
Rebalance->Rebalance:updateProcessQueueTableInRebalance.(1.remove the queue not belong here;2.when this client allocate a new queue,enqueue pull message request)
@enduml


