require 'jar_dependencies'
require_jar 'io.netty', 'netty-tcnative-boringssl-static', '1.1.33.Fork26'
require_jar 'com.alibaba', 'fastjson', '1.2.75'
require_jar 'org.apache.rocketmq', 'rocketmq-common', '4.8.0'
require_jar 'commons-beanutils', 'commons-beanutils', '1.9.2'
require_jar 'org.apache.rocketmq', 'rocketmq-logging', '4.8.0'
require_jar 'commons-validator', 'commons-validator', '1.6'
require_jar 'commons-digester', 'commons-digester', '1.8.1'
require_jar 'commons-collections', 'commons-collections', '3.2.2'
require_jar 'io.netty', 'netty-all', '4.1.63.Final'
require_jar 'org.apache.commons', 'commons-lang3', '3.11'
require_jar 'commons-logging', 'commons-logging', '1.2'
require_jar 'org.slf4j', 'slf4j-api', '1.7.25'
require_jar 'org.apache.rocketmq', 'rocketmq-remoting', '4.8.0'
require_jar 'org.apache.rocketmq', 'rocketmq-client', '4.8.0'

